name:  get tags

on:
  push:
    tags:
     - '[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY: docker.io
  REGISTRY_IMAGE: jpsevigny/jptest

jobs:
  get_versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.produce_output.outputs.versions }}    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: extract docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,format=long
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
      - 
        name: produce output
        id: produce_output
        run: |
          TAGS_JSON=$(cat <<'EOF'
          ${{ toJSON(fromJSON(steps.meta.outputs.json).tags) }}
          EOF
          )
          TAGS_JSON=$(echo $TAGS_JSON | tr '\n' ' ') | sed "s/${{env.REGISTRY}}\///g" | sed "s/${{env.REGISTRY_IMAGE}}\://g"
          echo "tags are $TAGS_JSON"
          echo "versions=$TAGS_JSON" >> "$GITHUB_OUTPUT"

  test_matrix:
    runs-on: ubuntu-latest
    needs: get_versions
    strategy:
        matrix:
            version: ${{ fromJSON(needs.get_versions.outputs.versions) }}
    steps:
      -
        name: echo matrix
        # create and sign "$version" manifest
        run: | 
          version=$(echo "${{matrix.version}}" | awk -F':' '{print $2}')
          echo "$version"